### ISSUE TITLE
Dataset contains very large unmasked value

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValTool_sample_data#24]
One of the datasets has a very large unmasked value (`5.813931e+36`), which causes issues with the multimodel statistics.

```
# Loading #15: esmvaltool_sample_data/data/timeseries/CMIP6/CMIP/E3SM-Project/E3SM-1-1/historical/r1i1p1f1/Amon/ta/gr/v20191211
#     cube.shape=(780, 2, 2, 2) cube.data.min()=235.27495 cube.data.max()=5.813931e+36
#     cube.coord("time").units.calendar='365_day'
```

**Comment by bouweandela** [comment]
Good find, could you please open a [dataset issue](https://github.com/ESMValGroup/ESMValCore/issues/new?assignees=valeriupredoi%2C+zklaus&labels=&template=data_issue_report.md&title=Dataset+problem%3A+) in the ESMValCore about it too?
