### ISSUE TITLE
Some datasets have multiple versions

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValTool_sample_data#5]
Some datasets have multiple versions, like the one below.

```
│   │               ├── CCCma
│   │               │   └── CanESM5
│   │               │       └── historical
│   │               │           └── r1i1p1f1
│   │               │               ├── Amon
│   │               │               │   └── ta
│   │               │               │       └── gn
│   │               │               │           ├── v20190306
│   │               │               │           └── v20190429
│   │               │               └── day
│   │               │                   └── ta
│   │               │                       └── gn
│   │               │                           ├── v20190306
│   │               │                           └── v20190429
```

**Comment by bouweandela** [comment]
It looks like specifying `latest=True` as an argument to [`pyesgf.search.connection.SearchConnection.new_context`](https://esgf-pyclient.readthedocs.io/en/latest/api.html#pyesgf.search.connection.SearchConnection.new_context) on this line
https://github.com/ESMValGroup/ESMValTool_sample_data/blob/d5cee8960cf71ce7a35b8743ad49580cb9d8dab1/esmvaltool_sample_data/sample_data.py#L136
does not have the expected result of only returning the latest datasets.
