### ISSUE TITLE
Datasets have different calendars / shapes

### ISSUE THREAD

**Issue by stefsmeets** [ESMValGroup/ESMValTool_sample_data#6]
The datasets have different lengths of the time axis, different calendars, and different horizontal axes. This makes them difficult to group and work with.

- `CMIP6/CMIP/NIMS-KMA/KACE-1-0-G/historical/r1i1p1f1/Amon/ta/gr/v20191028`
shape: `(1980, 2, 2, 1)`, calendar: `360_day`
- `CMIP6/CMIP/KIOST/KIOST-ESM/historical/r1i1p1f1/Amon/ta/gr1/v20191104`
shape: `(1980, 2, 2, 1)`, calendar: `365_day`
- `CMIP6/CMIP/NCAR/CESM2-WACCM/historical/r1i1p1f1/Amon/ta/gn/v20190227`
shape: `(1980, 2, 3, 2)`, calendar: `365_day`
- `CMIP6/CMIP/NASA-GISS/GISS-E2-1-H/historical/r1i1p1f1/Amon/ta/gn/v20190403`
shape: `(1368, 2, 1, 1)`, calendar: `365_day`
- `CMIP6/CMIP/CSIRO/ACCESS-ESM1-5/historical/r1i1p1f1/Amon/ta/gn/v20191115`
shape: `(780, 2, 2, 1)`, calendar: `proleptic_gregorian`
- `CMIP6/CMIP/NOAA-GFDL/GFDL-ESM4/historical/r1i1p1f1/Amon/ta/gr1/v20190726`
shape: `(780, 2, 2, 2)`, calendar: `365_day`
- `CMIP6/CMIP/CMCC/CMCC-CM2-SR5/historical/r1i1p1f1/Amon/ta/gn/v20200616`
shape: `(780, 2, 3, 2)`, calendar: `365_day`
- `CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Amon/ta/gn/v20190429`
shape: `(1980, 2, 2, 1)`, calendar: `365_day`
- `CMIP6/CMIP/BCC/BCC-CSM2-MR/historical/r1i1p1f1/Amon/ta/gn/v20181126`
shape: `(1020, 2, 2, 2)`, calendar: `365_day`
- `CMIP6/CMIP/INM/INM-CM4-8/historical/r1i1p1f1/Amon/ta/gr1/v20190605`
shape: `(780, 2, 1, 2)`, calendar: `365_day`
- `CMIP6/CMIP/NCC/NorESM2-MM/historical/r1i1p1f1/Amon/ta/gn/v20191108`
shape: `(780, 2, 3, 2)`, calendar: `365_day`
- `CMIP6/CMIP/E3SM-Project/E3SM-1-1/historical/r1i1p1f1/Amon/ta/gr/v20191211`
shape: `(780, 2, 2, 2)`, calendar: `365_day`
- `CMIP6/CMIP/CAS/FGOALS-f3-L/historical/r1i1p1f1/Amon/ta/gr/v20190927`
shape: `(780, 2, 2, 2)`, calendar: `365_day`
- `CMIP6/CMIP/NASA-GISS/GISS-E2-1-G/historical/r1i1p1f1/Amon/ta/gn/v20180827`
shape: `(1368, 2, 1, 1)`, calendar: `365_day`
- `CMIP6/CMIP/MPI-M/MPI-ESM1-2-HR/historical/r1i1p1f1/Amon/ta/gn/v20190710`
shape: `(780, 2, 2, 3)`, calendar: `proleptic_gregorian`
- `CMIP6/CMIP/AS-RCEC/TaiESM1/historical/r1i1p1f1/Amon/ta/gn/v20200623`
shape: `(1980, 2, 3, 2)`, calendar: `365_day`
- `CMIP6/CMIP/INM/INM-CM5-0/historical/r1i1p1f1/Amon/ta/gr1/v20190610`
shape: `(780, 2, 1, 2)`, calendar: `365_day`
- `CMIP6/CMIP/NASA-GISS/GISS-E2-1-G-CC/historical/r1i1p1f1/Amon/ta/gn/v20190815`
shape: `(1368, 2, 1, 1)`, calendar: `365_day`
- `CMIP6/CMIP/CAS/FGOALS-g3/historical/r1i1p1f1/Amon/ta/gn/v20190818`
shape: `(804, 2, 1, 2)`, calendar: `365_day`
- `CMIP6/CMIP/NUIST/NESM3/historical/r1i1p1f1/Amon/ta/gn/v20190630`
shape: `(1980, 2, 1, 2)`, calendar: `gregorian`
- `CMIP6/CMIP/CAMS/CAMS-CSM1-0/historical/r1i1p1f1/Amon/ta/gn/v20190708`
shape: `(900, 2, 2, 2)`, calendar: `365_day`
- `CMIP6/CMIP/CMCC/CMCC-CM2-HR4/historical/r1i1p1f1/Amon/ta/gn/v20200904`
shape: `(780, 2, 3, 2)`, calendar: `365_day`
- `CMIP6/CMIP/NCAR/CESM2/historical/r1i1p1f1/Amon/ta/gn/v20190308`
shape: `(1980, 2, 3, 2)`, calendar: `365_day`
- `CMIP6/CMIP/CCCR-IITM/IITM-ESM/historical/r1i1p1f1/Amon/ta/gn/v20191226`
shape: `(780, 2, 1, 2)`, calendar: `julian`
- `CMIP6/CMIP/E3SM-Project/E3SM-1-0/historical/r1i1p1f1/Amon/ta/gr/v20191220`
shape: `(780, 2, 2, 2)`, calendar: `365_day`
- `CMIP6/CMIP/AWI/AWI-CM-1-1-MR/historical/r1i1p1f1/Amon/ta/gn/v20181218`
shape: `(780, 2, 2, 3)`, calendar: `proleptic_gregorian`
- `CMIP6/CMIP/THU/CIESM/historical/r1i1p1f1/Amon/ta/gr/v20200417`
shape: `(1980, 2, 3, 2)`, calendar: `365_day`
- `CMIP6/CMIP/NOAA-GFDL/GFDL-CM4/historical/r1i1p1f1/Amon/ta/gr1/v20180701`
shape: `(780, 2, 2, 2)`, calendar: `365_day`
- `CMIP6/CMIP/FIO-QLNM/FIO-ESM-2-0/historical/r1i1p1f1/Amon/ta/gn/v20191204`
shape: `(780, 2, 3, 2)`, calendar: `365_day`
- `CMIP6/CMIP/CCCma/CanESM5/historical/r1i1p1f1/Amon/ta/gn/v20190306`
shape: `(1980, 2, 2, 1)`, calendar: `365_day`
- `CMIP6/CMIP/IPSL/IPSL-CM6A-LR/historical/r1i1p1f1/Amon/ta/gr/v20180803`
shape: `(1980, 2, 2, 1)`, calendar: `gregorian`
- `CMIP6/CMIP/NCC/NorCPM1/historical/r1i1p1f1/Amon/ta/gn/v20200724`
shape: `(1980, 2, 2, 1)`, calendar: `365_day`
- `CMIP6/CMIP/HAMMOZ-Consortium/MPI-ESM-1-2-HAM/historical/r1i1p1f1/Amon/ta/gn/v20190627`
shape: `(780, 2, 1, 2)`, calendar: `proleptic_gregorian`
- `CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/Amon/ta/gn/v20190710`
shape: `(780, 2, 1, 2)`, calendar: `proleptic_gregorian`
- `CMIP6/CMIP/CAS/CAS-ESM2-0/historical/r1i1p1f1/Amon/ta/gn/v20200502`
shape: `(1980, 2, 2, 2)`, calendar: `365_day`
- `CMIP6/CMIP/MIROC/MIROC6/historical/r1i1p1f1/Amon/ta/gn/v20190311`
shape: `(780, 2, 1, 2)`, calendar: `gregorian`
- `CMIP6/CMIP/MRI/MRI-ESM2-0/historical/r1i1p1f1/Amon/ta/gn/v20190308`
shape: `(780, 2, 2, 2)`, calendar: `proleptic_gregorian`
- `CMIP6/CMIP/SNU/SAM0-UNICON/historical/r1i1p1f1/Amon/ta/gn/v20190323`
shape: `(780, 2, 3, 2)`, calendar: `365_day`
- `CMIP6/CMIP/NCC/NorESM2-LM/historical/r1i1p1f1/Amon/ta/gn/v20190815`
shape: `(780, 2, 2, 1)`, calendar: `365_day`
- `CMIP6/CMIP/E3SM-Project/E3SM-1-1-ECA/historical/r1i1p1f1/Amon/ta/gr/v20200624`
shape: `(780, 2, 2, 2)`, calendar: `365_day`
- `CMIP6/CMIP/BCC/BCC-ESM1/historical/r1i1p1f1/Amon/ta/gn/v20181217`
shape: `(1980, 2, 2, 1)`, calendar: `365_day`
- `CMIP6/CMIP/CSIRO-ARCCSS/ACCESS-CM2/historical/r1i1p1f1/Amon/ta/gn/v20191108`
shape: `(780, 2, 2, 1)`, calendar: `proleptic_gregorian`
- `CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/ta/gr/v20200310`
shape: `(780, 2, 3, 3)`, calendar: `proleptic_gregorian`

**Comment by Peter9192** [comment]
That's good right? That's realistic. Actually this is what was leading to all the bugs before, and it's partly the reason I wanted to clean up some of the time handling code in the multi-model module.

**Comment by stefsmeets** [comment]
It's not realistic if I the regridding and concatenation fails before the data even get to the multimodel tests. At this point I'd rather have a dataset that *must* work with the multimodel test and expand from there.

**Comment by stefsmeets** [comment]
Fixed by #7
